### ISSUE TITLE
Contrôle de rond-point

### ISSUE THREAD

**Issue by BulotF** [InseeFr/Umbrella#114]
# Business case
Cette issue complète la définition des ronds-points définie ici : 
-  https://github.com/InseeFr/Bowie/issues/42
Elle permet de définir des contrôles au niveau des ronds-points. Comme on souhaite avoir d'une part des contrôles valables pour 1 occurrence, comme des contrôles sur l'ensemble, certains développements s'inspirent des contrôles de tableau dynamique : https://github.com/InseeFr/Bowie/issues/94

Le besoin est explicité plus largement sur l'issue Lunatic ci-dessous.

## DDI
Un rond-point est défini comme une Sequence de typeOfSequence "roundabout" qui référence une Loop.
Les occurrences de cette Loop peuvent être filtrées où non.
Si elles sont filtrées, la Loop référence un IfThenElse qui référence une Sequence de typeOfSequence filteredLoopContent.
Si elles ne sont pas filtrées, la Loop référence une Sequence de typeOfSequence loopContent.

Les contrôles de niveau "rond-point" seront référencés dans la séquence de type "roundabout".
Les contrôles de niveau "occurrence" seront référencés dans la séquence de type "filteredLoopContent" ou "loopContent".
La définition de ces contrôles sera classique.

## Pogues

- https://github.com/InseeFr/Pogues/issues/792

## Pogues-model
La définition actuelle des rond-points permet déjà de leur attribuer des contrôles.
Au passage, changement de vocabulaire, reporté sur les contrôles de tableau dynamique : WHOLE / OCCURRENCE vient remplacer DYNAMIC_ARRAY / LINE.

## Eno : Pogues -> DDI + Eno DDI -> Lunatic

- https://github.com/InseeFr/Concevoir-Workplace/issues/15
- https://github.com/InseeFr/Eno/pull/1107

## Lunatic

- https://github.com/InseeFr/Lunatic/issues/1069

# Progress
Au 30/09/2024, reste la partie Eno DDI -> Lunatic

**Comment by AnneHuSKa** [comment]
@JulienCarmona voir comment conserver cette information de @BulotF
