### ISSUE TITLE
Variables de type Dates/durée découpée en 3 (DATE/DATEAAMM/DATEAAAA)

### ISSUE THREAD

**Issue by laurentC35** [InseeFr/Umbrella#115]
Bug à investiguer.

Message original:
> Pourquoi les variables dates et durées sont au format (<DATE> , <DATEAAMM> et <DATEAAAA> ) en sorti du fichier xml collecter. Alors qu'il ne s'agit que d'une seule variable dans le questionnaire ?

**Comment by laurentC35** [comment]
Le questionnaire créé dans Pogues contenant bien 3 questions qui collectent 3 variables.
Donc cohérent, en attente de retour pour fermer l'Issue

**Comment by JulienCarmona** [comment]
après échange poussé avec l'utilisateur, on se rend compte qu'il n'avait pas compris qu'il n'avait pas de problème
