### ISSUE TITLE
Bridging the feature gap for business surveys

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Umbrella#18]
# Business case
Today, corporate surveys use Xforms/Orbeon technology. They will "soon" use Lunatic. It is therefore necessary to ensure that the functional coverage of Pogues/Eno/Lunatic is at least that of Pogues/Eno/Xforms

# Stack

## Eno
- [ ] https://github.com/InseeFr/Eno/issues/491
- [ ] adapt ddi2lunatic
- [ ] https://github.com/InseeFr/Lunatic/issues/237

## Lunatic
- [ ] point out the missing components
- [ ] improve tables
- [ ] creation of missing components

# Progress

# Release date

**Comment by romaintailhurat** [comment]
Merged with https://github.com/InseeFr/Umbrella/issues/26
